[package]
name = "render_with_rust"
version = "0.1.0"
authors = ["Denver Ellis <dsellis@ualr.edu"]
edition = "2018"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"